opt_in_rules:
  - legacy_random
  - private_action
  - private_outlet
  - unneeded_pa​​rentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
line_length: 300
excluded: 
  - Pods

type_body_length:
  - 400
  - 600

variable_name_max_length:
  - 60 
  - 80 

